- name: install apache2
  hosts: ec2
  become: true
  tasks:
    - name: install
      apt:
        name: apache2
        state: present

    - name: restart
      apache2_module:
        name: rewrite
        state: present
      notify:
        - restart

    - name: change port to 8090
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 80"
        line: "Listen 8090"
        state: present
      notify: restart

    - name: Copy index.html to Apache2 HTML path
      copy:
        src: ./index.html
        dest: /var/www/html/index.html


  handlers:
    - name: restart
      service:
        name: apache2
        state: restarted 